CI now checks if a migration is missing  - Fail CI on main and tag releases if a new migration should be created due to changes in the db schema  - Add error msg to schema.prisma file if a migration is not created to reflect changes made to db schema, but do NOT fail action

diff --git a/.github/actions/setup-rust/action.yaml b/.github/actions/setup-rust/action.yaml
--- a/.github/actions/setup-rust/action.yaml
+++ b/.github/actions/setup-rust/action.yaml
@@ -67,7 +67,18 @@ runs:
       working-directory: core
       if: ${{ steps.cache-prisma-restore.outputs.cache-hit != 'true' }}
       shell: bash
-      run: cargo prisma generate
+      run: |
+        cargo prisma generate
+
+        # Check if a new migration should be created due to changes in the schema
+        cargo prisma migrate dev -n test --create-only --skip-generate
+        if git ls-files --others --exclude-standard | grep -q '^core/prisma/migrations/'; then
+          echo "::error file=core/prisma/schema.prisma,title=Missing migration::New migration should be generated due to changes in prisma schema"
+          # Fail action if we are on main or a release tag, to avoid releasing a app with broken db
+          if [ "$GITHUB_REF" == "refs/heads/main" ] || [[ "$GITHUB_REF" == refs/tags/* ]]; then
+            exit 1
+          fi
+        fi
 
     - name: Save Prisma codegen
       id: cache-prisma-save
