Fix migration check not always failing when it should on main  - Fix check due to Github using `refs/heads/gh-readonly-queue/main/` as ref when merging a PR from merge-queue to main  - Add migration due to changes made in #2161

diff --git a/.github/actions/setup-rust/action.yaml b/.github/actions/setup-rust/action.yaml
--- a/.github/actions/setup-rust/action.yaml
+++ b/.github/actions/setup-rust/action.yaml
@@ -75,10 +75,12 @@ runs:
         cargo prisma migrate dev -n test --create-only --skip-generate
         if git ls-files --others --exclude-standard | grep -q '^prisma/migrations/'; then
           echo "::error file=core/prisma/schema.prisma,title=Missing migration::New migration should be generated due to changes in prisma schema"
-          # Fail action if we are on main or a release tag, to avoid releasing a app with broken db
-          if [ "$GITHUB_REF" == "refs/heads/main" ] || [[ "$GITHUB_REF" == refs/tags/* ]]; then
-            exit 1
-          fi
+          case "$GITHUB_REF" in
+            "refs/heads/main" | "refs/heads/gh-readonly-queue/main/"* | "refs/tags/"*)
+              # Fail action if we are on main or a release tag, to avoid releasing an app with a broken db
+              exit 1
+              ;;
+          esac
         fi
 
     - name: Save Prisma codegen
