Fix autoformat CI & format codebase (#2581)
* Update pnpm version

* Fix autoformat

* Improve autoformat msg

* Attempt to fix autoformat 2

* Fix autoformat

* Ignore deleted files in auto-format

* Fix diff filter

* Autoformat whole codebase

* Improve error message for autoformat CI

* Test autoformat CI

* Revert "Test autoformat CI"

This reverts commit 0bf2f46d1aa19bec92d73d4d62c8156473455040.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,8 +25,14 @@ jobs:
     timeout-minutes: 7
     permissions: {}
     steps:
-      - name: Checkout repository
+      - name: 'PR commits + 1'
+        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
+
+      - name: 'Checkout PR branch and all PR commits'
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+          fetch-depth: ${{ env.PR_FETCH_DEPTH }}
 
       - name: Setup Node.js, pnpm and dependencies
         uses: ./.github/actions/setup-pnpm
@@ -38,10 +44,18 @@ jobs:
 
       - name: Perform style check
         run: |-
-          set -eux
-          pnpm autoformat only-frontend
-          if [ -n "$(git diff --name-only --cached)" ]; then
+          set -eu
+
+          pnpm autoformat only-frontend >/dev/null
+
+          _files="$(git diff --name-only --cached)"
+          if [ -n "$_files" ]; then
             echo "Some files are not correctly formatted. Please run 'pnpm autoformat' and commit the changes." >&2
+
+            while IFS= read -r _file || [ -n "$_file" ]; do
+              echo "::error file=${_file},title=Incorrectly formatted file::Please run 'pnpm autoformat' and commit the changes."
+            done < <(printf '%s' "$_files")
+
             exit 1
           fi
 
